### ISSUE TITLE
A random business name

### ISSUE THREAD

**Issue by ZendaInnocent** [devmedtz/django_saas#42]
When user register, a random business name is associated to the user.

Since business name is mandatory for any user, it should be filled on registration.

If possible can be added to a user model.

**Comment by devmedtz** [comment]
The business name should be blank = true and null = true, He/she should fill when login to their dashboard.

**Comment by ZendaInnocent** [comment]
If that is the case, its logic should be removed from sign up view.

**Comment by devmedtz** [comment]
The logic is, After user signup => login => fill business form, => Dashboard
